### ISSUE TITLE
unify ontology locations

### ISSUE THREAD

**Issue by VladimirAlexiev** [EIS-Bonn/Luzzu#20]
http://eis-bonn.github.io/Luzzu/ontologies.html points to ontologies at http://eis-bonn.github.io/Luzzu/ontologies/qpro/qpro.html etc. These point to downloads at http://eis-bonn.github.io/Luzzu/ontologies/qpro/qpro.ttl etc.

However, the canonic URLs http://purl.org/eis/vocab/qpro etc resolve to http://butterbur04.iai.uni-bonn.de/ontologies/qpro/qpro (and downloads also there). This creates the opportunity for discrepancies between the ontologies at different locations. Get rid of one set: keep only the purl locations.

**Comment by jerdeb** [comment]
Fixed
