### ISSUE TITLE
Luzzu IO Module ...FAILURE 

### ISSUE THREAD

**Issue by shakeel26** [EIS-Bonn/Luzzu#24]
After running the command mvn clean install in Framework directory I got the mentioned error. Before in the terminal there are some WARNINGs too but here at Luzzu IO Module it has failure becuase of that WEbapp is skipped and web UI isn't accessible. It is some dependencies error, can you please let me know how can i resolve ?
Thanks  

Luzzu IO Module .................................... FAILURE [  0.268 s]
[INFO] luzzu-webapp ....................................... SKIPPED
[INFO] Luzzu Communications Module ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.624 s
[INFO] Finished at: 2019-11-27T08:51:08+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project luzzu-io: Could not resolve dependencies for project io.github.luzzu:luzzu-io:jar:4.0.0: The following artifacts could not be resolved: org.rdfhdt:hdt-java-core:jar:2.1-SNAPSHOT, org.rdfhdt:hdt-jena:jar:2.1-SNAPSHOT: Could not find artifact org.rdfhdt:hdt-java-core:jar:2.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :luzzu-io

**Comment by jerdeb** [comment]
Hi,
This repository is not maintained anymore. For the latest versions of luzzu please use: https://github.com/Luzzu/Framework/

**Comment by shakeel26** [comment]
thank you for reply, I have tried the latest version also you mentioned above but igot the same error when doing mvn clean installation in Framework, here is what the error, can you please tell me how can I add the required dependencies ? Thanks in Advance 
[INFO] Luzzu IO Module .................................... FAILURE [  0.257 s]
[INFO] luzzu-webapp ....................................... SKIPPED
[INFO] Luzzu Communications Module ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.559 s
[INFO] Finished at: 2019-11-27T11:31:10+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project luzzu-io: Could not resolve dependencies for project io.github.luzzu:luzzu-io:jar:4.0.0: The following artifacts could not be resolved: org.rdfhdt:hdt-java-core:jar:2.1-SNAPSHOT, org.rdfhdt:hdt-jena:jar:2.1-SNAPSHOT: Could not find artifact org.rdfhdt:hdt-java-core:jar:2.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :luzzu-io
